# Generated by Django 3.0.3 on 2020-02-04 20:19

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Crime',
            fields=[
                ('id', models.IntegerField(primary_key=True, serialize=False)),
                ('offense_type', models.CharField(max_length=200)),
                ('offense_description', models.CharField(max_length=200)),
                ('report_date', models.DateTimeField()),
                ('offense_start_date', models.DateTimeField()),
                ('offense_end_date', models.DateTimeField()),
                ('block', models.CharField(max_length=200)),
                ('district', models.CharField(max_length=200)),
                ('beat', models.CharField(max_length=200)),
                ('census_tract', models.CharField(max_length=200)),
                ('longitude', models.DateTimeField()),
                ('latitude', models.FloatField()),
                ('time', models.IntegerField()),
            ],
        ),
    ]
