# Generated by Django 3.0.3 on 2020-02-04 21:03

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('crimesapp', '0002_auto_20200204_2040'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='crime',
            name='time',
        ),
    ]
