# Generated by Django 3.0.3 on 2020-02-04 21:06

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('crimesapp', '0003_remove_crime_time'),
    ]

    operations = [
        migrations.AlterField(
            model_name='crime',
            name='latitude',
            field=models.FloatField(null=True),
        ),
        migrations.AlterField(
            model_name='crime',
            name='longitude',
            field=models.FloatField(null=True),
        ),
        migrations.AlterField(
            model_name='crime',
            name='offense_end_date',
            field=models.DateTimeField(null=True),
        ),
        migrations.AlterField(
            model_name='crime',
            name='offense_start_date',
            field=models.DateTimeField(null=True),
        ),
        migrations.AlterField(
            model_name='crime',
            name='report_date',
            field=models.DateTimeField(null=True),
        ),
    ]
